<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10071" started-at="2021-09-02T18:01:01 CDT" finished-at="2021-09-02T18:01:11 CDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10071" started-at="2021-09-02T18:01:01 CDT" finished-at="2021-09-02T18:01:11 CDT">
      <class name="page.Month_Page">
        <test-method status="PASS" signature="month()[pri:0, instance:page.Month_Page@49e202ad]" name="month" duration-ms="26" started-at="2021-09-02T18:01:01 CDT" finished-at="2021-09-02T18:01:01 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- month -->
      </class> <!-- page.Month_Page -->
      <class name="test.AddCategory_TestPage">
        <test-method status="PASS" signature="AddCategory()[pri:0, instance:test.AddCategory_TestPage@1e9e725a]" name="AddCategory" duration-ms="9954" started-at="2021-09-02T18:01:01 CDT" finished-at="2021-09-02T18:01:11 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddCategory -->
      </class> <!-- test.AddCategory_TestPage -->
      <class name="test.Validate_Months">
        <test-method status="FAIL" signature="validateMonths()[pri:0, instance:test.Validate_Months@15d9bc04]" name="validateMonths" duration-ms="2" started-at="2021-09-02T18:01:11 CDT" finished-at="2021-09-02T18:01:11 CDT">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[12]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 12
at test.Validate_Months.validateMonths(Validate_Months.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMonths -->
      </class> <!-- test.Validate_Months -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
